### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by gnodar01**
This would allow us to actually [pass](https://github.com/gnodar01/core-test/runs/7398936206?check_suite_focus=true) the CI check, with all tests passing. Unfortunately, the reason the tests are not currently passing is because cellprofiler proper is needed in a subset of the tests. Including cellprofiler as an optional dependency in the "test" extra mitigates this. However, we are using ubuntu in the github action, so we have to build the wheel, and add in [linux build dependencies](https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-20.04) to do so, which is a bit painful because the whole thing takes like 45 minutes to run to completion. If we go this route, we should probably switch it to run on merge, instead of on push.

Should be noted that this reverses the recent python 3.9 support introduced in #92, because cellprofiler doesn't have the corresponding version upgrades of h5py and pyzmq, causing the CI to fail because of a dependency resolution error. Should be no problem to re-reverse it back, as long as we set the version numbers in both core and cellprofiler to the same version range.

An alternative to this PR would be to modify the github workflow, such that pytest just skips the subset of tests which rely on cellprofiler being installed (just in the yml file, they wouldn't be skipped when running locally). The CI would run quicker at the cost of a bit less code coverage.

### CODE REVIEW

**Comment by bethac07** [comment]
It looks to me like most of the tests that are failing are a) doing so on loading a pipeline (because the modules in the pipeline) and b) really need to just load and/or execute A pipeline rather than do anything fancy with THAT pipeline, so would it be better to just create a one-module pipeline that has the input modules and/or LoadData plus Align, which lives in this repo so that a "real" module can for testing? I'm definitely fine with skipping ~20 out of ~1400 tests, but with that I think we could skip just a very tiny number and never need CellProfiler here. 

(And if we DID decide we can live with CellProfiler as a test dependency, which I agree is worth avoiding, I would argue to do it by pip installing from GH master rather than PyPI; we nearly always bump dependencies across the two repos more-or-less synchronously, whereas we push to PyPI much less often. That would allows us to have better matrixing of our build env).

**Comment by gnodar01** [comment]
@bethac07 I've removed the necessity of a cellprofiler installation.
When cellprofiler is there, it will run the same tests as before, but when its not it will use some modified pipelines.
* [4bd010a](https://github.com/CellProfiler/core/pull/104/commits/4bd010abc571e7d166fe6058056f45d8393ff79d) just creates a slimmer pipeline with only input modules.
* [9cc0ba7](https://github.com/CellProfiler/core/pull/104/commits/9cc0ba7b714c951f73788f18e215559326c5732d) does the same, but I created core-only versions of the cppipe and json files
* [8ba5844](https://github.com/CellProfiler/core/pull/104/commits/8ba5844bcb8c47a50c5216af4e617be44def762a) was a bit trickier. I created a slimmer pipeline with `IdentifyPrimaryObjects` and `MeasureObjectSizeShape` removed, but I couldn't just remove `FlipAndRotate` because some of the tests had decent amount of reliance on it, especially around setting a dummy `display_post_group` method on it. So instead I just created a duplicated of the `flipandrotate.py` file and put it in the `tests/worker` where `test_worker.py` lives. I know duplicating code = bad, but I figured even if the real `flipandrotate` module is modified in the future, we won't have to remember to modify the version that lives here, since we're not actually testing its ability to flip and rotate. Thoughts?

**Comment by bethac07** [comment]
> I know duplicating code = bad, but I figured even if the real flipandrotate module is modified in the future, we won't have to remember to modify the version that lives here, since we're not actually testing its ability to flip and rotate. Thoughts?

I agree that I think it's pretty unlikely that this does us any harm here, but since all we need is a module, not its functionality, is there a reason to not use the Align module, since that's the only "normal" module that lives in core? Otherwise, looks great to me!

**Comment by gnodar01** [comment]
> is there a reason to not use the Align module

Nope! Was just fixated on having identical test behavior as before when a cellprofiler installation was found, but yeah it's unnecessary even in that circumstance. Removed non-core modules altogether in [8eb8ebb](https://github.com/CellProfiler/core/pull/104/commits/8eb8ebb9525b952c6065ee2bedec61bfc5272459), in favor of `Align`.

**Review by bethac07 — APPROVED** [review]
I approve the heck out of this

**Pull request merged**
