### PR TITLE
Add Character Setting

### PR DESCRIPTION
**Pull request by hinerm**
Adds a simple Character Setting, an Alphanumeric subclass enforcing single-character constraints

This setting helps round out primitive type coverage.

### CODE REVIEW

**Comment by DavidStirling** [comment]
Is there a particular use-case for selecting `Boolean` over the existing `Binary` setting? It looks like both return a `bool`, so if you really need to set as 0 or 1 it may be simpler to just add handling for those in the existing class.

**Comment by hinerm** [comment]
@DavidStirling I didn't find `Binary` when I was writing this... I think I was looking for something called `Boolean` 🙄 

The numeric representation isn't required. I can just use a `Binary`.

**Comment by hinerm** [comment]
@DavidStirling I removed the Boolean setting - is there anything else you'd like to see before merging?

**Comment by DavidStirling** [comment]
Looks great, thanks!

**Pull request merged**
