### PR TITLE
Fix notes decoding

### PR DESCRIPTION
**Pull request by DavidStirling**
Fix CellProfiler/CellProfiler#4296

I think the best thing we can do here is strip out the problem characters from Notes fields when we encounter decoding problems. It won't look as pretty but should allow these pipelines to be loaded.

### CODE REVIEW

**Comment by bethac07** [comment]
Do you have a pipeline to test this with? I tried making my own in Python 2.2 but can't manage to get into the except loop.

**Comment by bethac07** [comment]
So, in my test case (attached below), I'm getting a bunch of â characters; we could add the following bit of code after the `except` to try to delete those.  Happy to try your test case when you upload.

```
                if len(value) >0:
                    for eachval in value:
                        if "â" in eachval:
                            eachval = eachval.replace("â","'")
```

[issues_4296.cpproj.zip](https://github.com/CellProfiler/core/files/5556472/issues_4296.cpproj.zip)

**Comment by bethac07** [comment]
(In my test case, all of the lists for module notes were only len 1, so value[1:-1] would never hit, FWIW.

**Comment by DavidStirling** [comment]
This bug applies to pipelines saved in 4.0+, sorry! The 'a' characters are a separate issue related to decoding old pipelines with the wrong codec, we should fix that as another PR at some point.

Here's the pipeline modified to replicate the issue. In 406 trying to load it will fail. In this PR the dodgy characters will be deleted instead so that loading succeeds.
[issues_4296_406.zip](https://github.com/CellProfiler/core/files/5556557/issues_4296_406.zip)

`value[1:-1]` is applied to the string form of the setting before we evaluate it into a list. It serves to remove the `[]` list container as after the replacement operation we apply `split` to produce a list instead.

**Comment by bethac07** [comment]
Sorry, it said "CP2 example pipelines" in the issue, so i thought that was what we were working with.  My mistake!

I will check this now, but is there any harm in adding both types of decoding fix in the same PR?

**Comment by DavidStirling** [comment]
Ah, good point. Perhaps this other issue came in recently. I don't think we strictly want to remove the 'a' characters, it'd be better to fix the decoding process entirely. I'll take a closer look tomorrow.

**Comment by bethac07** [comment]
Works nicely for me! Thanks @DavidStirling

**Pull request merged**
