### PR TITLE
Remove java dependencies from input modules

### PR DESCRIPTION
**Pull request by DavidStirling**
Requires CellProfiler/CellProfiler#4552

This PR's primary goal is to remove the hard dependency on Java and javabridge. This revolves around rewriting the input modules to perform image set generation in Python rather than with java objects. There are a lot of changes under the hood (see [this discussion thread](https://github.com/CellProfiler/CellProfiler/discussions/4492)), but the key points are as follows:

- Bumped version to 5.0.0 (project file format is incompatible with older versions).
- Replaced java-based functionality from input modules with a Python-based implementation.
  - The new implementation should have feature parity with CP4
  - "Extract Metadata from image file headers" has been moved from Metadata to Images.
  - Images now defines objects representing image planes, Metadata appends to those objects and NamesAndTypes sorts them into sets.
  - Between `prepare_run` and `run` stages image sets are now pickled/compressed and stored in the Image_Set_Blob measurement (previously a java object blob was stored).
  - Plane extraction in Images now provides granular options split planes on specific axes (C/Z/T) rather than all-or-nothing.
- Image file objects are now stored and handled using the new ImageFile and ImagePlane classes (replacing java ImagePlaneDetails).
- Image plane metadata now operates via a Python dictionary with support for custom keys.
- HDF5 storage of metadata now carries an array of image dimensions, rather than the entire (unused) OME-XML.
- HDF5FileList has been refactored:
  - Pathnames are now stored as raw text to create groups.
  - Filenames are now stored as an array of strings, retiring the obsolete VStringArray implementation.
  - As such, file list storage has changed and so .cpproj files from older versions cannot be loaded. Attempting to open these will just load the pipeline for convenience.
  - Manipulation of the file list has been optimised to improve performance when adding large numbers of files.
- Java now starts on demand, rather than when CellProfiler is launched.
- Introduced the new `cellprofiler_core.reader` base class to define custom image readers.
  - Bioformats and ImageIO-based readers have been created (these are existing dependencies).
  - The Reader class defines a Bioformats-like API to abstract out image reading functionality.
  - All javabridge calls should hopefully now be within python-bioformats rather than CellProfiler itself.
  - Additional readers can be loaded as plugins from the user's plugin directory.
  - `get_image_reader` utility function can be used to call for a reader to be chosen for an ImageFile object.
- Image loading now supports indexing with Series + CZT rather than only Series + Index (necessary for non-bioformats readers).
- Refactored Analysis mode functionality to support starting Java on demand. Details [here](https://github.com/CellProfiler/CellProfiler/wiki/Analysis-Mode-and-ZMQ-Interfaces).
  - An analysis Runner and it's ZMQ sockets now handle a single analysis run instead of being reused, which should prevent random freezes.
  - Inter-process communications have been optimised to reduce waiting times between jobs.
  - Analysis shutdown/cancel process has been improved to be cleaner and more reliable.

This is likely to need some thorough testing with actual image data, so perhaps moving towards a release candidate system like we did with CP4 would be a good road to take here.

I would suggest not squashing this PR if trying to merge it, the individual commit messages are probably more informative.

### CODE REVIEW

**Comment by bethac07** [comment]
In general, this is amazing and I adore it; one small corner case q though raised by another collaborator. I see that for cases where the thing is a URL and we're not reading via bioformats, we're [downloading as a temp file](https://github.com/CellProfiler/core/pull/97/files#diff-2bb423cb73765a65c26c073f6a3777d0fb26825523f50d1e86d296ab28acd23cR286-R315) so that then we can read with the base ImageFile. I definitely get why that makes sense, but was just also wondering about [just trying to read it into memory and skip the file](https://stackoverflow.com/questions/46343372/writing-to-s3-using-imageio-and-boto3#comment109077610_46343834) - do you have any thoughts? On the one hand, we eliminate a potential pain point about making files that we don't really need, but on the other, I'm worried about what happens here with ie a big file that we maybe don't WANT to read into memory all at once.

**Comment by DavidStirling** [comment]
The `download_to_temp_file` function is intended to replicate the [caching functionality](https://github.com/CellProfiler/python-bioformats/blob/c03fb0988caf686251707adc4332d0aff9f02941/bioformats/formatreader.py#L676-L700) from `python-bioformats`. A revised version was added in this PR so that it's available to all other readers if/when needed.

Usage of this system is determined by the `supports_url` attribute of the reader class, as seen [here](https://github.com/CellProfiler/core/blob/ab65cecaf576d14c0d30070aecfb2c67d14e1995/cellprofiler_core/image/abstract_image/file/_file_image.py#L218-L219). Readers are therefore capable of specifying an alternate means of handling online files if the need arises.

I figure that the intention with the original bioformats implementation is to avoid the scenario where a truly massive file is pointed to which can't fit into memory. The `copyfileobj` function should automatically chunk large file downloads to avoid that problem, so it does strike me as the 'safer' option even if reading directly into memory would work for most cases and provide a performance improvement.

Perhaps implementing this on a reader-by-reader basis might provide a good balance. There's no reason that a reader couldn't be set up to accept URLs and read them directly.

**Comment by bethac07** [comment]
Totally makes sense, and what you've written is a very reasonable place to start since it's safer (users are more likely to run out of memory than disk space IME), if we want the other functionality later we can always add it on.

**Comment by DavidStirling** [comment]
> I've been successfully building (with local changes) CellProfiler, by running "pip install ." in the core repository directory then in the CellProfiler repo directory prior to switching to branches containing these PRs. Any insight would be most welcome!

Sorry @emmarogge , I'm not sure I follow here. To my understanding `pip install .` should build the current repo and install it as a package into site-packages. This would mean that subsequently switching branch would have little impact on your python environment as the source code is not being read directly at run time. Did you mean to use `pip install -e .` ('editable' mode), which would mean that the source code can be modified as you please?

If that's not the case, would you mind posting the result from running `pip list`? Thanks

**Comment by emmarogge** [comment]
> Did you mean to use pip install -e . ('editable' mode), which would mean that the source code can be modified as you please?
You are correct. I meant to run the install with `-e` in order to test that my changes will work once your changes have been merged in. Thank you!

**Comment by emmarogge** [comment]
I've now rebuilt CellProfiler (from your PRs) successfully and run it locally. This has resulted in the expected error (because no Image Reader class for Google Cloud Storage URLs exists): 

```
Choosing reader for r08c05f01p01-ch2sk1fk1fl1.tiff
Selected <class 'cellprofiler_core.readers.bioformats_reader.BioformatsReader'>
Downloading image from gs://fc-5fb69193-ff7c-4c2c-a251-c1861942beda/source_4_images/images/2020_11_04_CPJUMP1/images/BR00116991__2020-11-05T19_51_35-Measurement1/BR00116991__2020-11-05T19_51_35-Measurement1/Images/r08c05f01p01-ch2sk1fk1fl1.tiff
Error detected during run of module LoadData
...
```

This error message seems to indicate, to me, that CellProfiler is still relying on the Java Bioformats library under the hood to process image URLs when loaded via CSV into the LoadData module. Is that correct?

**Comment by DavidStirling** [comment]
```
gs://fc-5fb69193-ff7c-4c2c-a251-c1861942beda/source_4_images/images/2020_11_04_CPJUMP1/images/BR00116991__2020-11-05T19_51_35-Measurement1/BR00116991__2020-11-05T19_51_35-Measurement1/Images/r08c05f01p01-ch2sk1fk1fl1.tiff
```

`gs://` isn't a supported URL schema in CellProfiler at the moment. With the changes in this PR CellProfiler has a selection of image readers and there's a process to select one for a target file path. In this case the '.tiff' at the end of the URL is sufficient for the BioFormats reader to attempt to give it a go (and no alternative reader is found). BioFormats can't read that URL and so the load fails. There's no helpful error because the failure occurs within the Java code for BioFormats and doesn't get passed back to CellProfiler.

To add Google storage support you'd want to define a new `Reader` subclass which detects the 'gs' schema and gives itself priority by returning `1` from the `supports_format` method. You'll then want to implement your own methods for reading in the data.

Fortunately this is exactly the kind of scenario which the reader system is intended to provide a solution for. Hope that helps

**Comment by emmarogge** [comment]
It seems like there are remaining assumptions about filepaths/URLs in certain parts of CellProfiler that make this more complex than simply creating a new reader class. I've specifically run into problems related to the `cache_file` method in `_file_image.py`, which expects a bunch of arguments that are not required in the abstract parent class (channel, z, t, series, index, rescale, channel names...). Any insight about how I can circumvent this issue would be very helpful, since the TIFF GCS URL reader class I've created doesn't take those arguments for its read method.

**Comment by emmarogge** [comment]
David, have you been able to build & run this version of CellProfiler (and the core module) in a Docker container? It's important for my use case that I can run the version of CellProfiler with your changes & mine in a container so I'm hoping to validate that a Docker issue I'm having (ModuleNotFound error for cellprofiler_core despite its successful installation) is due to my changes alone.

**Comment by DavidStirling** [comment]
I've not tried it with Docker, but it sounds like you may have the wrong version of core installed in the container (could it be pulling the latest release from pip)?

**Comment by emmarogge** [comment]
> I've not tried it with Docker, but it sounds like you may have the wrong version of core installed in the container (could it be pulling the latest release from pypi)?

I am installing the correct version, as I have actually inspected the code itself in my Docker container and it has my GCS changes. Could you please try to build with Docker to see if you also encounter any issues?

**Comment by emmarogge** [comment]
Thank you for the debugging suggestion -- I have found that the location of cellprofiler_core seen by python is "/core/cellprofiler_core/__init__.py", which is what I would expect when installing it from source (a local clone of my Github repository). It seems likely that Python is not aware of this location and if I can figure that piece out, I predict that I'll be able to run CellProfiler in the container with my changes. I'll update once I have more progress to report.

**Review by gnodar01 — APPROVED** [review]

**Pull request merged**
