### PR TITLE
Add function for pure export of grouping tags

### PR DESCRIPTION
**Pull request by bethac07**

### CODE REVIEW

**Comment by bethac07** [comment]
@gnodar01 Do you think as part of this PR and/or later we should rename the previous function (which returns grouping tags if they exist, and if not, metadata tags) from `get_grouping_tags` to `get_grouping_or_metadata_tags`? I feel like it will make it less likely to cause confusion later.

**Comment by gnodar01** [comment]
> Do you think as part of this PR and/or later we should rename the previous function ... from `get_grouping_tags` to `get_grouping_or_metadata_tags`

I was thinking something like:

```
    def get_grouping_tags(self):
        """Get the metadata tags that were used to group the image set,
        and only those, not metadata instead
        """
        if not self.has_feature(EXPERIMENT, M_GROUPING_TAGS,):
            return []

        return json.loads(self.get_experiment_measurement(M_GROUPING_TAGS))

    def get_grouping_tags_or_metadata(self):
        """Get the metadata tags that were used to group the image set,
        with metadata fallback
        """
        return self.get_grouping_tags() or self.get_metadata_tags()
```

but to your point, since the proposed `get_grouping_tags_or_metadata` is already currently called `get_grouping_tags`, it may make more sense to go with the `get_grouping_tags_only /  get_grouping_tags_or_metadata` approach.

**Comment by gnodar01** [comment]
There's 50 warning, I think all are related to dividing by 0, and therefore producing nans. Are we okay with those, or for that matter, or we reliant on those nan values downstream?

**Comment by bethac07** [comment]
I 100% get what you're saying, my personal feeling is that if we were writing this new we'd do it your way but I'm a bit hesitant to reuse an old name onto a new function. I think it's highly unlikely though that it would be an issue, so if you'd rather go with what is ultimately a cleaner naming scheme, definitely fine with me.

**Comment by gnodar01** [comment]
> I'm a bit hesitant to reuse an old name onto a new function

Okay, I'm leaning that way as well. Let's go with `get_grouping_tags_only / get_grouping_tags_or_metadata` then. Do you want to push your existing changes?

**Review by gnodar01 — APPROVED** [review]

**Pull request merged**
